export { default as Home } from "./Home"
export { default as SignUp } from "./SignUp"
export { default as SignIn } from "./SignIn"
export { default as Dashboard } from "./Dashboard"
export { default as DashboardEdit } from "./DashboardEdit"
